version: '3.8'

services:
  mysql_db1:
    image: mysql:latest
    container_name: mysql_container_1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pj-ms-user
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    networks:
      - my_network

  mysql_db2:
    image: mysql:latest
    container_name: mysql_container_2
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3308:3306"
    networks:
      - my_network
networks:
  my_network:
    driver: bridge
